---
# tasks file for apache2

- name: install apache2 and related packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_wsgi

- name: enable apache service and start up it
  service:
    name: httpd
    enabled: yes
    state: started
