---
# tasks file for redis-server

- name: enable epel repository
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: install redis server
  yum:
    name: redis
    state: present

- name: enable redis server service for every boot and start it right now
  systemd:
    name: redis
    enabled: yes
    state: started
    daemon_reload: yes
  ignore_errors: yes
